name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: Windows,   os: windows-latest, target: windows }
          - { name: macOS,     os: macos-latest,   target: macos }
          - { name: iOS,       os: macos-latest,   target: ios }
          - { name: Android32, os: ubuntu-latest,  target: android32 }
          - { name: Android64, os: ubuntu-latest,  target: android64 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          export-pdb: true
          build-args: --config RelWithDebInfo
          bindings-ref: main
          combine: true
          target: ${{ matrix.config.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.config.name }}
          path: dist
